version: '3.4'

services:
  e-commerceproduct.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductapi
    container_name: E-CommerceProduct.API
    build:
      context: .
      dockerfile: E-CommerceProductAPI\Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  e-commerceproduct.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: E-CommerceProduct.DB
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd123!@#
    volumes:
      - ./.containers/E-CommerceProduct-db:/var/opt/mssql/data
    depends_on:
      - e-commerceproduct.api
    ports:
      - "1433:1433"