version: '3.4'

services:
  e-commerceproduct.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductapi
    container_name: E-CommerceProduct.Api
    build:
      context: .
      dockerfile: E-CommerceProductAPI\Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  e-commerceproduct.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CommerceProduct.DB
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./.containers/E-CommerceProduct-db:/var/opt/mssql
    ports:
      - "1433:1433"